os: Visual Studio 2015

platform: x64

configuration: Release

skip_tags: true

environment:
    MINICONDA_ROOT: C:\Miniconda36-x64

install:
  - ps: $env:COMMIT_TIMESTAMP = git log -1 --pretty=format:%ct

  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  
  - cmd: call %MINICONDA_ROOT%\Scripts\activate root
  - cmd: conda config --append channels conda-forge
  - cmd: conda create -y --name default --clone root
  - cmd: conda install -y -q conda-build
  
  - cmd: cd C:\ && git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg && bootstrap-vcpkg.bat && cd %APPVEYOR_BUILD_FOLDER%
  
build_script:
  - cmd: conda metapackage pairinteraction-dependencies %COMMIT_TIMESTAMP% --no-anaconda-upload --dependencies "pyqt 5.6.0" "numpy 1.13.1" "scipy 0.19.1" "psutil 5.2.2" "pint 0.8.1" "pyzmq 16.0.2"
  
  - cmd: C:\vcpkg\vcpkg install sqlite3:x64-windows eigen3:x64-windows boost:x64-windows gsl:x64-windows zeromq:x64-windows

after_build:
  - cmd: activate default
  - cmd: conda clean -y -a
  - cmd: conda install -y -q pairinteraction-dependencies --use-local
  - cmd: md conda-export\noarch
  - cmd: md conda-export\win-64
  - cmd: move %MINICONDA_ROOT%\pkgs\*.tar.bz2 conda-export\win-64
  - cmd: conda list -e > conda-spec-file.txt
  - cmd: activate root
  - cmd: conda index conda-export\noarch
  - cmd: conda index conda-export\win-64
  - cmd: 7z a -tzip python-packages-windows-x86_64.zip conda-export conda-spec-file.txt > nul
    
  - cmd: C:\vcpkg\vcpkg export sqlite3:x64-windows eigen3:x64-windows boost:x64-windows gsl:x64-windows zeromq:x64-windows --raw
  - cmd: move C:\vcpkg\vcpkg-export-* vcpkg-export
  - cmd: 7z a -tzip cpp-libraries-windows-x86_64.zip vcpkg-export > nul
  
artifacts:
  - path: cpp-libraries-windows-x86_64.zip
    name: cpp-libraries-windows-x86_64
  - path: python-packages-windows-x86_64.zip
    name: python-packages-windows-x86_64

deploy:
  - provider: GitHub
    release: $(COMMIT_TIMESTAMP)
    auth_token: $(GH_TOKEN)
    artifact: cpp-libraries-windows-x86_64, python-packages-windows-x86_64
    force_update: true
    on:
      branch: master
