language: generic

skip_tags: true

matrix:
  include:
    - os: osx
      osx_image: xcode8
      before_install:
        - COMMIT_TIMESTAMP=$(git log -1 --pretty=format:%ct)
        - echo $COMMIT_TIMESTAMP
        - wget https://repo.continuum.io/miniconda/Miniconda3-4.3.11-MacOSX-x86_64.sh -O miniconda.sh
        - chmod +x miniconda.sh && ./miniconda.sh -b -p /Users/travis/miniconda3 && source /Users/travis/miniconda3/bin/activate root
        - conda config --append channels conda-forge
        - conda install -y -q conda-build
        - conda clean -y -a
      install:
        - conda metapackage pairinteraction-dependencies $COMMIT_TIMESTAMP --no-anaconda-upload --dependencies "pyqt 5.6.0" "numpy 1.12.1" "scipy 0.19.0" "psutil 5.2.2" "pint 0.8.1"
        - conda install -y -q pairinteraction-dependencies --use-local 
      script:
        - mkdir conda-export
        - mkdir conda-export/noarch
        - mkdir conda-export/osx-64
        - mv /Users/travis/miniconda3/pkgs/*.tar.bz2 conda-export/osx-64
        - conda index conda-export/noarch
        - conda index conda-export/win-64
        - zip -r -X python-packages-osx conda-export
      before_deploy:
        - git tag $COMMIT_TIMESTAMP
        - git push --quiet --tags "https://pairinteraction-slave:${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"

deploy:
  provider: releases
  release: $COMMIT_TIMESTAMP
  prerelease: false
  api_key: $GH_TOKEN
  file_glob: true
  file: $TRAVIS_BUILD_DIR/python-packages-osx.zip
  skip_cleanup: true
  on:
    branch: master
