language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      before_install:
        - COMMIT_TIMESTAMP=$(git log -1 --pretty=format:%ct)
        - echo $COMMIT_TIMESTAMP
        - wget https://repo.continuum.io/miniconda/Miniconda3-4.3.11-MacOSX-x86_64.sh -O miniconda.sh
        - chmod +x miniconda.sh && ./miniconda.sh -b -p $HOME/miniconda3 && source $HOME/miniconda3/bin/activate root
        - conda config --append channels conda-forge
      install:
        - conda create -y --name default --clone root
        - conda install -y -q conda-build
      script:
        - conda metapackage pairinteraction-dependencies $COMMIT_TIMESTAMP --no-anaconda-upload --dependencies pyqt numpy scipy psutil pint pyzmq

        - source activate default
        - conda clean -y -a
        - conda install -y -q nomkl pairinteraction-dependencies --use-local
        - mkdir conda-export
        - mkdir conda-export/noarch
        - mkdir conda-export/osx-64
        - mv /Users/travis/miniconda3/pkgs/*.tar.bz2 conda-export/osx-64
        - conda list -e > conda-spec-file.txt
        
        - source activate root
        - conda index conda-export/noarch
        - conda index conda-export/osx-64

        - zip -r -X python-packages-osx conda-export conda-spec-file.txt
      before_deploy:
        - git tag -f $COMMIT_TIMESTAMP
        - git push --quiet --tags "https://pairinteraction-slave:${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"

branches:
  only:
    - master

deploy:
  provider: releases
  release: $COMMIT_TIMESTAMP
  prerelease: false
  api_key: $GH_TOKEN
  file_glob: true
  file: $TRAVIS_BUILD_DIR/python-packages-osx.zip
  skip_cleanup: true
  on:
    branch: master
